import { lesson, q } from './helpers.mjs'

export const roboticsSections = [
  lesson(
    'Robotics Overview',
    [
      'Robotics is the interdisciplinary field that combines mechanical engineering, electrical engineering, computer science, and control theory to design machines that can sense, decide, and act in the physical world. A robot is typically defined as a programmable machine capable of carrying out a series of actions autonomously or semi-autonomously. Unlike fixed automation, robots are built to operate with varying degrees of flexibility across tasks, environments, and payloads.',
      'The history of robotics spans from early industrial arms in manufacturing plants to modern autonomous drones, surgical assistants, and warehouse mobile robots. Early robots focused on repetitive, dangerous, or precision tasks that humans could not perform consistently at scale. Today, robotics applications extend into agriculture, logistics, healthcare, exploration, defense, and consumer products such as vacuum cleaners and educational kits.',
      'Robots are classified by mobility (fixed, mobile, aerial, underwater), application domain (industrial, service, medical), and autonomy level. Fixed industrial arms weld and assemble products on factory lines, while mobile robots navigate warehouses and hospitals. Autonomy ranges from teleoperated systems with human control to fully autonomous platforms that plan paths and react to unexpected obstacles without direct human input.',
      'Core capabilities of any robotic system include perception (understanding the environment through sensors), cognition (processing data and making decisions), and actuation (moving or manipulating objects through motors and mechanisms). Software architectures often separate low-level motor control from high-level task planning. Communication between subsystems may use buses such as CAN, Ethernet, or ROS-based middleware in research and advanced commercial platforms.',
      'The robotics industry continues to grow as component costs fall and algorithms improve. Key drivers include labor shortages, demand for precision and traceability in manufacturing, and the need for automation in hazardous environments. Success in robotics projects requires balancing performance, cost, safety, and maintainability rather than pursuing maximum capability in every dimension.',
      'Learning robotics provides a foundation for careers in automation, embedded systems, AI, and mechatronics. Whether building a simple line-following robot or deploying a fleet of autonomous mobile robots, the same principles of sensing, control, and safe integration apply. Understanding the full stack—from mechanical design to software—helps engineers troubleshoot failures and design systems that work reliably in real-world conditions.',
    ],
    [
      q(
        'What three core capabilities define most robotic systems?',
        ['Perception, cognition, and actuation', 'HTML, CSS, and JavaScript', 'Welding, painting, and packaging', 'GPS, Wi-Fi, and Bluetooth only'],
        0,
        'Robots sense the world (perception), decide what to do (cognition), and move or manipulate (actuation).',
      ),
      q(
        'How is a robot generally distinguished from fixed automation?',
        ['Robots are programmable and can adapt to varying tasks or environments', 'Robots never use sensors', 'Fixed automation is always mobile', 'Robots cannot operate in factories'],
        0,
        'Programmability and flexibility across tasks or conditions are hallmarks of robotic systems.',
      ),
      q(
        'Which field is NOT typically considered part of robotics?',
        ['Pure literary criticism', 'Mechanical engineering', 'Computer science', 'Control theory'],
        0,
        'Robotics draws on engineering and computing disciplines, not humanities fields like literary criticism.',
      ),
      q(
        'What is an example of a mobile robot application?',
        ['Warehouse inventory transport', 'Fixed welding on an assembly line', 'A non-moving CNC mill', 'A manual screwdriver'],
        0,
        'Mobile robots move through environments; warehouse AMRs are a common example.',
      ),
      q(
        'What does higher autonomy in a robot generally mean?',
        ['Less need for continuous direct human control during operation', 'No sensors required', 'No software required', 'The robot cannot be reprogrammed'],
        0,
        'Greater autonomy means the system can plan and react with reduced real-time human intervention.',
      ),
      q(
        'Why did early industrial robots gain adoption in manufacturing?',
        ['They performed repetitive or hazardous tasks consistently at scale', 'They replaced all human workers immediately', 'They required no maintenance', 'They were cheaper than any manual tool'],
        0,
        'Repeatability, safety, and throughput in repetitive tasks drove early industrial robot use.',
      ),
      q(
        'Which pairing correctly matches robot type to example?',
        ['Fixed arm — automotive welding cell', 'Aerial robot — stationary conveyor', 'Underwater robot — office printer', 'Medical robot — traffic light'],
        0,
        'Fixed industrial arms are widely used for welding and assembly in automotive production.',
      ),
      q(
        'What role does cognition play in a robot?',
        ['Processing sensor data and deciding actions', 'Supplying electrical power only', 'Physical movement without software', 'Manufacturing mechanical parts'],
        0,
        'Cognition covers algorithms and logic that interpret inputs and choose behaviors.',
      ),
      q(
        'Which trend has helped expand robotics into new markets?',
        ['Falling component costs and improved algorithms', 'Elimination of all safety standards', 'Removal of all sensors from robots', 'Banning software updates'],
        0,
        'Cheaper sensors, compute, and better AI/control have broadened feasible applications.',
      ),
      q(
        'Why is interdisciplinary knowledge valuable in robotics?',
        ['Failures often span mechanical, electrical, and software layers', 'Only software ever fails', 'Mechanical design is unrelated to control', 'Sensors do not affect programming'],
        0,
        'Real robots integrate many domains; debugging requires understanding the full stack.',
      ),
    ],
  ),
  lesson(
    'Robot Components',
    [
      'A complete robot is built from interconnected subsystems that work together as an integrated platform. The mechanical structure provides the frame, joints, and end effectors that define how the robot physically interacts with its environment. Structural materials range from aluminum extrusions and steel for industrial arms to carbon fiber and plastics for lightweight drones and research platforms.',
      'The power subsystem supplies energy to all components, typically through batteries for mobile robots or mains power for fixed installations. Power distribution includes regulators, fuses, and battery management systems that protect cells and ensure stable voltage to sensitive electronics. Undersized power systems cause brownouts during peak motor demand, leading to resets or control instability.',
      'The compute subsystem runs operating systems, control loops, perception algorithms, and high-level planners. Embedded microcontrollers handle real-time motor control, while single-board computers or industrial PCs run navigation and vision. Many designs use a hierarchical architecture with a fast low-level controller and a slower high-level processor communicating over serial or network links.',
      'Actuators convert electrical commands into motion or force at joints and wheels. Common types include brushed and brushless DC motors, stepper motors, servo motors, and linear actuators. Gearboxes and belt drives often reduce speed and increase torque to match load requirements. End effectors—grippers, tools, vacuum cups—determine what the robot can manipulate.',
      'Sensors provide feedback about the robot and its surroundings. Encoders report joint position, IMUs measure orientation, and proximity or vision sensors detect objects. Wiring harnesses, connectors, and communication buses tie hardware together; poor cabling is a frequent source of intermittent faults in deployed systems.',
      'Software and firmware bind hardware into a functioning system. Bootloaders, device drivers, real-time schedulers, and application code must align with the physical layout of components. Documenting the bill of materials, pin assignments, and calibration procedures is essential for maintenance, upgrades, and team handoffs in professional robotics projects.',
    ],
    [
      q(
        'What does the mechanical structure of a robot primarily provide?',
        ['Frame, joints, and physical interaction hardware', 'Only software algorithms', 'Internet connectivity', 'User interface graphics'],
        0,
        'Mechanical structure defines physical form, motion axes, and how the robot contacts the world.',
      ),
      q(
        'Why is power subsystem sizing critical in robotics?',
        ['Peak motor loads can cause brownouts if power is insufficient', 'Robots never draw variable current', 'Batteries are only decorative', 'Voltage never affects electronics'],
        0,
        'Motors can draw large transient current; inadequate supply causes resets and erratic behavior.',
      ),
      q(
        'What is a typical division of compute responsibilities?',
        ['Microcontroller for real-time control; higher-level CPU for planning and perception', 'One LED for all computation', 'No compute needed for actuators', 'Only cloud servers on the robot'],
        0,
        'Hierarchical compute separates hard real-time motor loops from slower planning tasks.',
      ),
      q(
        'Which component converts electrical commands into physical motion?',
        ['Actuator', 'Encoder', 'Fuse', 'Heat sink only'],
        0,
        'Actuators such as motors and linear drives produce motion or force from electrical input.',
      ),
      q(
        'What is an end effector?',
        ['Tool or gripper at the robot interface with the workpiece', 'Main battery pack', 'Operating system kernel', 'Emergency stop button only'],
        0,
        'End effectors are the hands or tools that perform manipulation tasks.',
      ),
      q(
        'What information do encoders typically provide?',
        ['Joint or wheel position and sometimes velocity', 'Ambient temperature only', 'Wi-Fi signal strength', 'Battery chemistry type'],
        0,
        'Encoders measure rotational or linear displacement for closed-loop control.',
      ),
      q(
        'Why can wiring harness quality affect robot reliability?',
        ['Flexing, vibration, and poor connectors cause intermittent faults', 'Wires never fail in robots', 'All robots use wireless power only', 'Cabling is unrelated to sensors'],
        0,
        'Physical deployment stresses cables; bad harness design leads to difficult intermittent errors.',
      ),
      q(
        'What does a battery management system (BMS) help protect?',
        ['Battery cells from overcharge, over-discharge, and unsafe conditions', 'Only the robot paint finish', 'Software license keys', 'Mechanical bearings exclusively'],
        0,
        'A BMS monitors cell health and limits operating conditions to keep packs safe and long-lived.',
      ),
      q(
        'Which material is common for lightweight robot frames in research platforms?',
        ['Aluminum extrusions or carbon fiber', 'Untreated paper', 'Glass only', 'Concrete blocks'],
        0,
        'Aluminum and carbon fiber offer favorable strength-to-weight for many mobile and lab robots.',
      ),
      q(
        'Why document pin assignments and calibration in robot builds?',
        ['Maintenance, upgrades, and team handoffs depend on accurate hardware records', 'Documentation slows all robots down', 'Firmware auto-discovers everything always', 'Calibration never changes after shipping'],
        0,
        'Clear records reduce debugging time and errors when hardware or personnel change.',
      ),
    ],
  ),
  lesson(
    'Mechanical Systems',
    [
      'Mechanical design determines a robot\'s reachable workspace, payload capacity, speed, and accuracy. Kinematics describes motion without considering forces: for a robot arm, forward kinematics computes end-effector pose from joint angles, while inverse kinematics finds joint angles for a desired pose. Mobile robots use wheeled, legged, or tracked locomotion, each with trade-offs in terrain handling, efficiency, and complexity.',
      'Degrees of freedom (DOF) count independent motions a mechanism can perform. A planar robot arm may have two or three DOF, while a six-axis industrial arm offers full position and orientation control in 3D space. Redundant DOF can improve obstacle avoidance and singularity handling but complicate control and calibration.',
      'Transmission elements—gears, belts, lead screws, and harmonic drives—match motor speed and torque to application needs. Gear ratios increase torque at the expense of speed and may introduce backlash, which hurts precision in positioning tasks. Direct-drive motors reduce backlash but require larger motors and drivers for the same torque output.',
      'Structural stiffness and damping affect vibration and settling time after moves. Lightweight arms may oscillate after rapid stops unless controllers or mechanical design compensate. Bearing selection, joint preload, and frame geometry all influence repeatability measured in millimeters or sub-millimeter tolerances for industrial applications.',
      'End-of-arm tooling must be designed for the workpiece geometry, weight, and required forces. Parallel jaw grippers, vacuum cups, and custom fixtures each suit different parts. Tool changers allow one arm to swap between operations, increasing flexibility on a production line without adding more robots.',
      'Simulation and CAD tools help validate reach, collisions, and cycle time before building hardware. Maintenance considerations include lubrication schedules, wear on belts and bearings, and access panels for service. A mechanically sound design reduces control effort and extends the operational life of the full robotic system.',
    ],
    [
      q(
        'What does inverse kinematics compute for a robot arm?',
        ['Joint angles needed to achieve a desired end-effector pose', 'Battery voltage from motor speed', 'Wi-Fi latency', 'Ambient humidity'],
        0,
        'Inverse kinematics maps desired tool pose to required joint configurations.',
      ),
      q(
        'What does degrees of freedom (DOF) describe?',
        ['Independent motions a mechanism can perform', 'Number of color sensors', 'Total weight of the robot', 'Hours of battery life only'],
        0,
        'DOF counts independent axes of motion, such as revolute or prismatic joints.',
      ),
      q(
        'What is a common trade-off when using gear reduction?',
        ['Higher torque but lower speed and possible backlash', 'Higher speed with no mechanical change', 'Elimination of all vibration', 'No effect on motor loading'],
        0,
        'Gears trade speed for torque and may add backlash that affects precision.',
      ),
      q(
        'Why might a six-axis industrial arm be chosen over a simpler arm?',
        ['It can orient and position the tool fully in 3D workspace', 'It uses no electricity', 'It cannot reach overhead', 'It has zero maintenance needs'],
        0,
        'Six-axis arms provide full spatial positioning and orientation for complex tasks.',
      ),
      q(
        'Which locomotion type often handles rough terrain better than plain wheels?',
        ['Tracked or legged systems', 'Casters only on smooth glass', 'Fixed base with no movement', 'Passive skids'],
        0,
        'Tracks and legs improve mobility on uneven surfaces compared to standard wheels.',
      ),
      q(
        'What problem can insufficient structural stiffness cause?',
        ['Vibration and poor settling after moves', 'Faster battery charging', 'Automatic software updates', 'Increased Wi-Fi range'],
        0,
        'Flexible structures oscillate, requiring time to settle and harming precision.',
      ),
      q(
        'What is backlash in a mechanical drive?',
        ['Play or lost motion between meshing components', 'Maximum motor temperature', 'Sensor sampling rate', 'Emergency stop response'],
        0,
        'Backlash is clearance in gears or couplings that causes positioning error on direction changes.',
      ),
      q(
        'Why use a tool changer on an industrial arm?',
        ['Swap end effectors for multiple operations without separate robots', 'Increase battery capacity', 'Remove need for sensors', 'Disable safety interlocks'],
        0,
        'Tool changers let one arm perform diverse tasks by exchanging grippers or tools.',
      ),
      q(
        'What does forward kinematics determine?',
        ['End-effector pose from known joint angles', 'Joint angles from desired pose', 'Motor supplier pricing', 'Network IP address'],
        0,
        'Forward kinematics computes tool position and orientation from joint variables.',
      ),
      q(
        'Why validate reach and collisions in CAD before building?',
        ['Catch mechanical interferences and unreachable poses early', 'Replace all safety training', 'Eliminate need for actuators', 'Guarantee infinite payload'],
        0,
        'CAD simulation reduces costly rework by revealing workspace and collision issues upfront.',
      ),
    ],
  ),
  lesson(
    'Electronics Basics',
    [
      'Robotic electronics begin with power: batteries or AC supplies feed regulators that provide stable voltages (commonly 3.3 V, 5 V, 12 V, 24 V, or 48 V depending on the platform). Decoupling capacitors near integrated circuits reduce noise from switching loads. Grounding and power return paths must be designed to avoid ground loops and voltage drops that confuse sensor readings.',
      'Microcontrollers and motor drivers form the interface between software and physical actuators. H-bridges control DC motor direction and speed; ESCs (electronic speed controllers) drive brushless motors in drones and high-performance drives. Stepper drivers chop current to hold precise rotor positions for applications like 3D printers and small positioning stages.',
      'Digital logic levels define how sensors and processors communicate. Many boards use 3.3 V I/O; connecting 5 V signals without level shifting can damage pins. Protocols such as I2C, SPI, UART, and CAN each suit different bandwidth, distance, and wiring complexity requirements across a robot\'s sensor network.',
      'Analog circuits amplify and filter sensor signals before analog-to-digital conversion. Op-amps, voltage dividers, and RC filters condition outputs from strain gauges, thermistors, and raw photodiodes. Sampling rate and resolution of ADCs determine how faithfully fast phenomena—such as motor current spikes—are captured for control and diagnostics.',
      'Protection circuits include fuses, TVS diodes, and reverse-polarity protection to survive wiring mistakes and inductive kickback from motors. Flyback diodes or MOSFET body diodes shunt energy when inductive loads switch off. ESD precautions during assembly protect sensitive semiconductors on workbenches and in the field.',
      'Schematic capture, PCB layout, and cable management translate design intent into reliable hardware. Keep high-current motor wiring separate from sensitive analog sensor lines to reduce electromagnetic interference. Testing with multimeters, oscilloscopes, and logic analyzers verifies power rails and signals before integrating software on new robot electronics.',
    ],
    [
      q(
        'Why place decoupling capacitors near IC power pins?',
        ['They reduce high-frequency noise from switching loads', 'They increase motor torque directly', 'They replace batteries', 'They store program code'],
        0,
        'Local capacitors supply transient current and filter noise on power rails near chips.',
      ),
      q(
        'What does an H-bridge circuit typically control?',
        ['DC motor direction and speed', 'Only ambient light level', 'GPS satellite count', 'Mechanical gear ratio'],
        0,
        'H-bridges switch polarity and PWM to drive bidirectional DC motors.',
      ),
      q(
        'Why is level shifting important between 5 V and 3.3 V devices?',
        ['Prevents damage and ensures valid logic thresholds', 'Increases battery weight only', 'Eliminates need for ground', 'Makes all signals analog'],
        0,
        'Mixed-voltage systems need translation so higher voltages do not harm 3.3 V I/O pins.',
      ),
      q(
        'Which protocol is commonly used for multi-node automotive and industrial buses on robots?',
        ['CAN', 'HTTP only', 'FTP', 'SMTP'],
        0,
        'CAN bus is robust for distributed motor drives and sensors in many robotic platforms.',
      ),
      q(
        'What is the purpose of a flyback diode across an inductive load?',
        ['Shunt kickback voltage when the load switches off', 'Increase supply voltage permanently', 'Convert AC to DC only', 'Measure temperature'],
        0,
        'Diodes protect switches from voltage spikes produced when inductive current is interrupted.',
      ),
      q(
        'What do ADC resolution and sampling rate affect?',
        ['Fidelity of digitized sensor signals', 'Mechanical arm length', 'Paint color of the chassis', 'Number of mechanical joints'],
        0,
        'Higher resolution and appropriate sampling capture sensor dynamics accurately for control.',
      ),
      q(
        'Why separate high-current motor wiring from analog sensor lines?',
        ['Reduce electromagnetic interference on sensitive measurements', 'Increase cable cost only for aesthetics', 'Motors do not emit fields', 'Sensors prefer motor noise'],
        0,
        'Motor currents create fields and voltage drops that corrupt low-level sensor signals if bundled poorly.',
      ),
      q(
        'What does a battery management system monitor in robotic packs?',
        ['Cell voltage, current, temperature, and safe operating limits', 'Only user passwords', 'HTML page layout', 'Gear lubrication schedule'],
        0,
        'BMS hardware protects lithium packs and reports state of charge and health.',
      ),
      q(
        'Which tool helps visualize fast, time-varying electrical signals during debug?',
        ['Oscilloscope', 'Tape measure', 'Torque wrench', 'Calipers only'],
        0,
        'Oscilloscopes show voltage waveforms needed to diagnose timing and noise issues.',
      ),
      q(
        'What is reverse-polarity protection designed to prevent?',
        ['Damage when power connections are wired with incorrect polarity', 'All software bugs', 'Mechanical wear on bearings', 'Loss of kinematic calibration'],
        0,
        'Protection circuits block or limit current when supply polarity is connected backwards.',
      ),
    ],
  ),
  lesson(
    'Sensors in Robotics',
    [
      'Sensors enable robots to measure internal state and external conditions. Proprioceptive sensors report the robot\'s own configuration: encoders on joints, motor current for torque estimation, and IMUs combining accelerometers and gyroscopes for orientation. Without proprioception, closed-loop control cannot correct errors from load variation or surface friction.',
      'Exteroceptive sensors observe the environment. Lidar scans distance in 2D or 3D; cameras capture intensity and color for vision; ultrasonic and infrared sensors measure proximity at lower cost. Sensor choice depends on range, accuracy, update rate, lighting conditions, and whether the target is reflective, transparent, or moving.',
      'Sensor fusion combines multiple sources into a consistent estimate of pose or object location. Kalman filters and particle filters merge IMU data with wheel odometry or GPS for mobile robots. Vision fused with depth sensors improves obstacle detection compared to either modality alone, especially in cluttered or partially observed spaces.',
      'Calibration aligns sensor outputs with physical units and the robot\'s coordinate frames. Camera intrinsics and extrinsics must be known for accurate projection; lidar-to-base transforms require careful measurement. miscalibrated sensors cause navigation drift, grasp misalignment, and false collision alerts that are difficult to diagnose without systematic calibration routines.',
      'Noise, latency, and failure modes must be handled in software. Filters smooth jittery readings but add delay; aggressive filtering can destabilize fast control loops. Redundant sensors and plausibility checks detect stuck or drifting channels, allowing graceful degradation or safe stops when data is unreliable.',
      'Emerging sensor technologies—including solid-state lidar, event cameras, and tactile skins—expand what robots can perceive. Tactile sensors measure contact force and slip at fingertips, enabling delicate manipulation. Selecting sensors is a systems engineering task: each added sensor increases cost, wiring, compute load, and calibration burden.',
    ],
    [
      q(
        'What is proprioceptive sensing?',
        ['Measuring the robot\'s own internal state such as joint angles', 'Reading only external weather', 'Detecting user passwords', 'Monitoring internet bandwidth'],
        0,
        'Proprioception covers internal variables like position, velocity, and orientation of the robot body.',
      ),
      q(
        'Which sensor is well suited for 2D distance mapping in indoor navigation?',
        ['Lidar', 'Microphone only', 'Barometer alone', 'Passive RFID tag without reader'],
        0,
        '2D lidar produces scan data widely used for SLAM and obstacle avoidance indoors.',
      ),
      q(
        'Why fuse IMU data with wheel odometry on mobile robots?',
        ['Improve pose estimates when individual sources drift or slip', 'Eliminate all sensors', 'Increase motor voltage', 'Disable emergency stops'],
        0,
        'Fusion compensates for IMU drift and wheel slip by combining complementary error characteristics.',
      ),
      q(
        'What does camera extrinsic calibration define?',
        ['Transform between camera frame and robot base or world frame', 'Pixel color depth only', 'Battery cell chemistry', 'Motor winding resistance'],
        0,
        'Extrinsics relate where the camera sits and points relative to the robot coordinate system.',
      ),
      q(
        'What is a common failure mode if lidar hits transparent glass untreated?',
        ['Weak or missing returns causing map errors', 'Automatic perfect mapping', 'Increased torque at joints', 'Faster battery charging'],
        0,
        'Transparent or reflective surfaces can produce absent or false range readings.',
      ),
      q(
        'What do tactile sensors at a gripper primarily measure?',
        ['Contact force, pressure, or slip during manipulation', 'Global GPS position', 'Ambient sound level only', 'Network latency'],
        0,
        'Tactile sensing supports delicate grasp control and slip detection at contact.',
      ),
      q(
        'Why can aggressive sensor filtering harm control performance?',
        ['Added latency may destabilize fast feedback loops', 'Filtering always improves stability', 'Filters remove need for actuators', 'Filters increase mechanical stiffness'],
        0,
        'Heavy filtering delays measurements, which can hurt timely correction in dynamic control.',
      ),
      q(
        'Which IMU components help estimate orientation?',
        ['Accelerometers and gyroscopes', 'Only thermistors', 'Only microphones', 'Only pressure pads'],
        0,
        'Accelerometers sense gravity direction; gyroscopes measure angular rate for orientation tracking.',
      ),
      q(
        'What is a plausibility check on sensor data used for?',
        ['Detect stuck, out-of-range, or inconsistent readings', 'Paint the robot chassis', 'Compile high-level code', 'Increase gear backlash'],
        0,
        'Software checks flag bad data so the system can reject or replace unreliable measurements.',
      ),
      q(
        'When choosing sensors for a robot, what systems trade-off must be considered?',
        ['Cost, wiring, compute load, and calibration versus perception benefit', 'Only sensor color', 'Only brand logo size', 'Number of HTML pages'],
        0,
        'Each sensor adds integration work; engineers balance capability against system complexity.',
      ),
    ],
  ),
  lesson(
    'Motors and Actuators',
    [
      'Motors are the primary actuators that produce rotation in robotic joints and wheels. Brushed DC motors are simple and inexpensive but wear due to commutator contact; brushless DC (BLDC) motors offer higher efficiency and longevity with more complex drive electronics. Motor selection starts with required torque, speed, duty cycle, and thermal limits at the worst-case load.',
      'Stepper motors move in discrete steps and hold position without continuous feedback in many open-loop applications. They excel in low-speed positioning such as 3D printer axes but can lose steps under excessive load unless closed-loop stepper or encoder feedback is added. Servo motors integrate motor, gearbox, and control into units common in hobby and light industrial arms.',
      'Linear actuators produce straight-line motion for lifts, clamps, and adjustable fixtures. Hydraulic and pneumatic actuators deliver very high force for heavy industrial tasks but require pumps, compressors, and fluid handling. Electric linear actuators with lead screws or belt drives are cleaner and easier to control programmatically.',
      'Motor controllers translate command signals into phase currents or PWM duty cycles. Field-oriented control (FOC) for BLDC motors improves efficiency and smooth torque production. Current limiting protects drivers and motors from stall overheating; tuning PID loops on velocity and position channels determines tracking accuracy and responsiveness.',
      'Gearboxes trade speed for torque and affect backlash and efficiency. Harmonic drives offer high reduction in compact packages common in robot wrists; planetary gears handle higher torque in drive wheels. Direct-drive joints remove gearbox backlash for sensitive force control in collaborative and research manipulators at the cost of larger motors.',
      'Thermal management and maintenance extend actuator life. Continuous operation near stall current heats windings and magnets, demagnetizing or insulating failure over time. Bearing lubrication, belt tension checks, and monitoring driver fault flags are routine tasks that keep motion subsystems reliable in production environments.',
    ],
    [
      q(
        'What advantage do brushless DC motors typically offer over brushed DC?',
        ['Higher efficiency and longer life without commutator wear', 'No need for any driver electronics', 'They only work underwater', 'They cannot be speed-controlled'],
        0,
        'BLDC motors avoid brush wear and often run more efficiently with proper controllers.',
      ),
      q(
        'When can stepper motors lose position accuracy?',
        ['Under excessive load causing missed steps in open-loop mode', 'Never, under any condition', 'Only when powered off', 'When using encoders always'],
        0,
        'Open-loop steppers can skip steps if torque demand exceeds capability without feedback correction.',
      ),
      q(
        'What does field-oriented control (FOC) improve for BLDC motors?',
        ['Efficiency and smooth torque production', 'Wi-Fi signal strength', 'Camera frame rate', 'Battery packaging size only'],
        0,
        'FOC optimally orients current in the motor for better torque and efficiency.',
      ),
      q(
        'Why use a gearbox with a motor in robotics?',
        ['Increase output torque while reducing speed to match load needs', 'Eliminate all electrical power', 'Remove need for controllers', 'Increase backlash intentionally for precision'],
        0,
        'Gear reduction matches high-speed, low-torque motor characteristics to application loads.',
      ),
      q(
        'What is a primary risk of prolonged motor stall?',
        ['Overheating windings and potential damage', 'Automatic calibration improvement', 'Increased sensor accuracy', 'Reduced cable wear'],
        0,
        'Stall draws high current without cooling airflow, overheating the motor and driver.',
      ),
      q(
        'Which actuator type is common for high-force industrial presses and heavy lifts?',
        ['Hydraulic or pneumatic actuators', 'Tiny hobby servos only', 'LED indicators', 'Passive springs without control'],
        0,
        'Fluid power actuators deliver very large forces in heavy industrial applications.',
      ),
      q(
        'What does a servo motor package typically integrate?',
        ['Motor, gearbox, and control electronics in one unit', 'Only a passive hinge', 'Only a camera sensor', 'Only a lidar scanner'],
        0,
        'Servo units combine motion and control for simplified integration in lighter-duty systems.',
      ),
      q(
        'Why might direct-drive joints be chosen in collaborative manipulators?',
        ['Low backlash enables sensitive force control and smooth interaction', 'They eliminate all safety requirements', 'They require no power', 'They cannot be programmed'],
        0,
        'Direct drive improves force transparency important for safe human-robot collaboration.',
      ),
      q(
        'What does current limiting in a motor driver protect against?',
        ['Overcurrent damage during stalls or shorts', 'All software bugs automatically', 'Mechanical lubrication loss', 'Network timeouts'],
        0,
        'Limiting current reduces heat and component stress during fault or overload conditions.',
      ),
      q(
        'Where are harmonic drives often used in robot arms?',
        ['Compact high-reduction joints such as wrists', 'Battery charging circuits only', 'User display panels', 'Emergency lighting'],
        0,
        'Harmonic drives provide high ratio reduction in small volumes suited to articulated wrists.',
      ),
    ],
  ),
  lesson(
    'Control Systems',
    [
      'Control systems regulate robot behavior so outputs track desired commands despite disturbances. Open-loop control sends fixed commands without measuring results—simple but vulnerable to load changes and friction variation. Closed-loop control uses sensor feedback to compute errors and apply corrections continuously, enabling accuracy and disturbance rejection.',
      'PID (proportional-integral-derivative) controllers are widely used for joint velocity and position loops. Proportional gain reduces current error; integral gain eliminates steady-state offset; derivative gain dampens overshoot. Tuning requires balancing responsiveness against oscillation and noise amplification from derivative action on noisy signals.',
      'Multi-axis arms cascade control loops: an outer position loop feeds desired velocity to an inner velocity loop, which outputs torque or current commands. Feedforward terms anticipate known dynamics such as gravity torque on links, improving tracking without relying solely on feedback correction after errors occur.',
      'State-space and model-based methods represent system dynamics explicitly for advanced control. Computed torque control uses a dynamic model to linearize nonlinear arm equations. Linear quadratic regulators and model predictive control optimize performance over horizons subject to constraints on torque, speed, or workspace limits.',
      'Digital implementation samples sensors at fixed intervals; sample rate must exceed roughly ten times the loop bandwidth for stable discrete control. Aliasing and transport delay from filters or communication buses phase-shift the loop and can cause instability if not accounted for in design and tuning.',
      'Safety limits—maximum velocity, torque caps, and workspace boundaries—are enforced in control software and hardware interlocks. Monitoring tracking error and driver faults triggers holds or emergency stops. Robust control design assumes sensors fail, payloads vary, and surfaces slip, planning degraded modes rather than assuming ideal conditions.',
    ],
    [
      q(
        'What distinguishes closed-loop from open-loop control?',
        ['Closed-loop uses sensor feedback to correct errors', 'Closed-loop never uses sensors', 'Open-loop always adapts to load changes', 'Open-loop requires lidar'],
        0,
        'Feedback measures output error and adjusts commands in closed-loop systems.',
      ),
      q(
        'What does the integral term in a PID controller primarily address?',
        ['Steady-state error over time', 'Instantaneous noise only', 'Mechanical backlash elimination', 'Battery state of charge'],
        0,
        'Integral action accumulates error to remove persistent offset between setpoint and measurement.',
      ),
      q(
        'Why use cascaded position and velocity loops on a robot joint?',
        ['Separate fast inner torque/velocity control from slower position tracking', 'Eliminate all sensors', 'Increase open-loop stepper use only', 'Disable feedforward'],
        0,
        'Cascaded loops assign appropriate bandwidth: inner loops handle dynamics, outer loops set trajectory.',
      ),
      q(
        'What is feedforward control used for?',
        ['Anticipate known disturbances like gravity using a model', 'Replace all feedback permanently', 'Measure ambient temperature only', 'Increase communication latency'],
        0,
        'Feedforward applies predicted compensation so feedback handles remaining unmodeled error.',
      ),
      q(
        'Why must digital control sample rates be sufficiently high?',
        ['Discrete sampling introduces delay and aliasing that can destabilize loops', 'Low rates always improve stability', 'Sampling is unrelated to control', 'High rates remove need for actuators'],
        0,
        'Too-slow sampling approximates poorly and limits achievable loop bandwidth safely.',
      ),
      q(
        'What does model predictive control (MPC) optimize?',
        ['Future trajectories subject to dynamics and constraint limits', 'Only historical log files', 'Paint color schedules', 'User email routing'],
        0,
        'MPC plans control actions over a horizon while respecting constraints on states and inputs.',
      ),
      q(
        'What can excessive derivative gain cause with noisy sensors?',
        ['Amplified noise leading to jittery control output', 'Perfect noise rejection always', 'Mechanical lubrication', 'Increased battery capacity'],
        0,
        'Derivative action responds to rate of error; noise spikes produce large undesirable commands.',
      ),
      q(
        'What is computed torque control based on?',
        ['Dynamic model of the robot to cancel nonlinearities', 'Random number generation', 'Static HTML templates', 'Manual crank operation only'],
        0,
        'Computed torque uses modeled dynamics to decouple and linearize joint behavior.',
      ),
      q(
        'Why enforce torque and velocity limits in control software?',
        ['Protect hardware and maintain safe operation near people and equipment', 'Slow robots intentionally below safe speeds always', 'Eliminate calibration needs', 'Increase tracking error deliberately'],
        0,
        'Limits prevent mechanical damage and reduce hazard energy during faults or collisions.',
      ),
      q(
        'What should robust robot control assume about real operation?',
        ['Payloads vary, sensors fail, and surfaces slip', 'Perfect models and no disturbances', 'Infinite actuator bandwidth', 'Zero latency on all buses'],
        0,
        'Practical controllers plan for uncertainty, faults, and degraded modes instead of ideal conditions.',
      ),
    ],
  ),
  lesson(
    'Robot Programming',
    [
      'Robot programming spans low-level firmware on microcontrollers to high-level application code on PCs or cloud systems. Languages include C/C++ for real-time control, Python for prototyping and ROS nodes, and domain-specific languages such as RAPID for ABB or KRL for KUKA industrial arms. The choice depends on latency requirements, team skills, and vendor ecosystem.',
      'The Robot Operating System (ROS) provides messaging, tooling, and libraries widely used in research and increasingly in products. Nodes publish and subscribe to topics; services handle request-response patterns; actions manage long-running tasks with feedback. ROS 2 improves real-time support and security compared to ROS 1, aligning better with commercial deployment needs.',
      'Motion programming defines trajectories in joint space or Cartesian space. Waypoints specify positions, velocities, and accelerations; planners interpolate smooth paths respecting kinematic and dynamic limits. Offline programming in simulation allows teaching paths on virtual models before downloading to shop-floor robots, reducing downtime.',
      'Behavior trees and finite state machines organize high-level task logic such as pick-place sequences, error recovery, and mode switching. Clear state structure prevents ambiguous transitions when sensors disagree or operators request interrupts. Logging and structured error codes speed diagnosis when production cells halt unexpectedly.',
      'Real-time constraints separate hard real-time motor loops (microseconds to milliseconds) from soft real-time planning (tens to hundreds of milliseconds). Running everything on one general-purpose OS without isolation can cause missed deadlines and jerky motion. RTOS kernels, dedicated cores, or coprocessors isolate critical timing paths.',
      'Version control, continuous integration, and hardware-in-the-loop testing treat robot software like any safety-critical codebase. Unit tests validate kinematics and planners; integration tests run against simulators or bench rigs before touching production hardware. Documented APIs between mechanical, electrical, and software teams reduce integration friction during bring-up.',
    ],
    [
      q(
        'Why is C/C++ commonly used in low-level robot control?',
        ['It supports deterministic, efficient real-time execution on embedded hardware', 'It cannot access hardware timers', 'It replaces all need for sensors', 'It is only for web pages'],
        0,
        'C/C++ offers fine control over timing and resources needed for motor control loops.',
      ),
      q(
        'What problem do ROS topics primarily solve?',
        ['Decoupled publish-subscribe communication between software modules', 'Physical motor wiring', 'Battery cell manufacturing', 'Mechanical gear cutting'],
        0,
        'Topics let nodes exchange data asynchronously without tight pairwise coupling.',
      ),
      q(
        'What is offline robot programming?',
        ['Developing and validating paths in simulation before shop-floor deployment', 'Writing code without any computer', 'Disabling all safety systems', 'Programming only while motors run at full speed'],
        0,
        'Offline programming reduces production downtime by testing motions virtually first.',
      ),
      q(
        'Why use behavior trees for high-level robot logic?',
        ['They structure tasks, recovery, and mode changes clearly', 'They eliminate all sensors', 'They replace inverse kinematics', 'They are required by all batteries'],
        0,
        'Behavior trees modularize decision logic for complex, interruptible robot tasks.',
      ),
      q(
        'What is a hard real-time control loop?',
        ['One where missing deadlines can cause unsafe or unstable behavior', 'Any loop written in Python only', 'A loop that runs once per day', 'A loop with no timing requirements'],
        0,
        'Hard real-time tasks must complete within strict bounds every cycle for safe motion.',
      ),
      q(
        'What does a motion planner typically respect when generating trajectories?',
        ['Kinematic and dynamic limits on velocity, acceleration, and workspace', 'Only user interface colors', 'HTML tag nesting rules', 'DNS record TTL'],
        0,
        'Planners interpolate paths that stay within mechanical and actuator constraints.',
      ),
      q(
        'What improvement does ROS 2 offer over ROS 1 for products?',
        ['Better real-time behavior and security features', 'Elimination of all messaging', 'Removal of simulation tools', 'Mandatory cloud-only operation'],
        0,
        'ROS 2 targets production with DDS middleware, QoS, and improved real-time support.',
      ),
      q(
        'Why log structured error codes in production robot cells?',
        ['Speed diagnosis and recovery when lines stop unexpectedly', 'Increase motor temperature', 'Replace mechanical maintenance', 'Disable operator training'],
        0,
        'Clear logs and codes help maintenance teams identify fault causes quickly.',
      ),
      q(
        'What is hardware-in-the-loop (HIL) testing?',
        ['Running control software against simulated or partial hardware before full deployment', 'Testing only cardboard mockups without code', 'Skipping all integration tests', 'Operating without emergency stops'],
        0,
        'HIL validates software against realistic plant models or bench hardware safely.',
      ),
      q(
        'What is the difference between joint-space and Cartesian motion commands?',
        ['Joint-space moves individual axes; Cartesian specifies tool pose in workspace coordinates', 'They are identical always', 'Cartesian moves only battery cells', 'Joint-space is only for cameras'],
        0,
        'Joint commands target angles; Cartesian commands target end-effector position and orientation.',
      ),
    ],
  ),
  lesson(
    'Autonomous Navigation',
    [
      'Autonomous navigation enables mobile robots to move from start to goal while avoiding obstacles and respecting map constraints. Localization estimates the robot\'s pose in a known or partially known environment; mapping builds representations of that environment from sensor data. SLAM (Simultaneous Localization and Mapping) performs both concurrently when no prior map exists.',
      'Global planners compute coarse routes over occupancy grids, topological graphs, or road networks. Algorithms such as A*, Dijkstra, and RRT* find paths that avoid static obstacles and respect kinematic constraints. Local planners or trajectory trackers follow the global route while reacting to dynamic obstacles detected in real time by lidar, radar, or vision.',
      'Odometry integrates wheel rotations or visual motion for short-term pose updates but drifts over distance without global correction. GPS aids outdoor robots in open sky conditions; indoor systems rely on lidar scan matching, visual features, or AprilTag landmarks. Loop closure in SLAM detects revisits to previously mapped areas to reduce accumulated error.',
      'Dynamic obstacle avoidance uses velocity obstacles, dynamic window approach (DWA), or model predictive local planners to select collision-free velocities. Prediction of pedestrian or forklift motion improves safety in shared spaces. Speed and clearance margins are tuned to stopping distance given sensor latency and braking capability.',
      'Multi-robot coordination assigns tasks and deconflicts paths in warehouses and fulfillment centers. Central fleet managers reserve corridors; decentralized methods negotiate priorities locally. Communication drops require fallback behaviors such as conservative stopping or predefined holding zones to prevent collisions.',
      'Validation in simulation and staged real-world trials reduces risk before full autonomy deployment. Metrics include success rate, average mission time, minimum clearance, and frequency of human interventions. Regulatory and site-specific rules—speed limits, geofences, and restricted zones—must be encoded in maps and policy layers governing navigation stacks.',
    ],
    [
      q(
        'What does SLAM stand for and accomplish?',
        ['Simultaneous Localization and Mapping—building a map while tracking pose', 'Simple Linear Actuator Module', 'Static Lidar Adjustment Method', 'Software License And Maintenance'],
        0,
        'SLAM jointly estimates robot pose and environment structure from sensor streams.',
      ),
      q(
        'Why does wheel odometry alone drift over long distances?',
        ['Wheel slip and integration error accumulate without global corrections', 'Encoders are perfectly noise-free always', 'Odometry uses GPS indoors always', 'Maps cannot be updated'],
        0,
        'Small errors in each step integrate; slip on surfaces worsens long-horizon pose error.',
      ),
      q(
        'Which algorithm family is commonly used for grid-based global path planning?',
        ['A* and Dijkstra on occupancy grids', 'Bubble sort on motor lists', 'JPEG compression', 'RSA key exchange only'],
        0,
        'Graph search algorithms find minimum-cost paths over discretized free space.',
      ),
      q(
        'What is the role of a local planner in navigation?',
        ['Track the global path while reacting to nearby dynamic obstacles', 'Replace all sensors permanently', 'Calibrate battery cells only', 'Design mechanical gears'],
        0,
        'Local planners choose short-horizon motions safe against immediate detected obstacles.',
      ),
      q(
        'What is loop closure in SLAM?',
        ['Recognizing a revisited place to correct accumulated map and pose error', 'Closing all network ports', 'Shutting down motors each lap', 'Removing all landmarks'],
        0,
        'Loop closure aligns new observations with earlier map data to reduce drift.',
      ),
      q(
        'Why tune speed margins to stopping distance in shared spaces?',
        ['Sensor latency and braking limits require clearance before contact', 'Faster speed always improves safety', 'Margins are unrelated to lidar rate', 'Pedestrians never move unpredictably'],
        0,
        'Robots must stop within available distance given perception delay and deceleration capability.',
      ),
      q(
        'What indoor localization aid uses known visual fiducial markers?',
        ['AprilTag or similar landmark detection', 'Barometric altitude only', 'Ocean tide tables', 'Manual string measuring'],
        0,
        'Fiducial markers give precise pose updates when detected by cameras.',
      ),
      q(
        'What happens when fleet communication drops in coordinated navigation?',
        ['Fallback behaviors like conservative stops or holding zones should activate', 'Robots automatically teleport to goals', 'All maps are erased instantly', 'Motors run uncontrolled at max speed'],
        0,
        'Safe fallbacks prevent collisions when central coordination is unavailable.',
      ),
      q(
        'What does an occupancy grid represent?',
        ['Discretized cells labeled free, occupied, or unknown for planning', 'Motor temperature histogram only', 'User password hashes', 'HTML DOM tree'],
        0,
        'Grids encode where the robot can traverse based on mapped or sensed obstacles.',
      ),
      q(
        'Which metric helps evaluate autonomous navigation reliability before deployment?',
        ['Mission success rate and human intervention frequency', 'Logo brightness only', 'Cable color variety', 'Number of CSS files'],
        0,
        'Success and intervention rates quantify how often autonomy completes tasks safely alone.',
      ),
    ],
  ),
  lesson(
    'Industrial Automation',
    [
      'Industrial automation integrates robots into production lines for welding, assembly, painting, palletizing, and machine tending. Robots operate within cells defined by fences, light curtains, and interlocked doors that halt motion when breached. Cycle time, uptime, and quality metrics drive return on investment calculations for automation projects.',
      'Programmable logic controllers (PLCs) coordinate conveyors, sensors, and robots with deterministic scan cycles. Robots exchange signals with PLCs via digital I/O, fieldbus, or industrial Ethernet protocols such as Profinet and EtherNet/IP. Handshake sequences ensure parts are present and clamps secure before the robot begins a motion sequence.',
      'End-of-line testing, vision inspection, and traceability systems record serial numbers, torque values, and image evidence for each unit. When vision rejects a part, the cell routes it to rework or scrap without stopping the entire line if buffer and redundancy are designed correctly. Data integration with MES and ERP systems supports production analytics.',
      'Fixture design and part presentation critically affect robot success. Consistent part positioning reduces need for complex vision compensation; poorly toleranced inbound parts cause mis-picks and crashes. Quick-change tooling and standardized pallets shorten changeover between product variants in flexible manufacturing.',
      'Safety-rated monitored stop and speed reduction modes allow limited human access during certain steps under defined conditions. Lockout/tagout procedures protect maintenance staff during mechanical service. Risk assessments document hazards, severity, and mitigation per standards such as ISO 10218 and ISO/TS 15066 for collaborative applications.',
      'Retrofitting legacy lines with robots requires studying existing bottlenecks and interfaces. Simulation of throughput and reach verifies that proposed cells meet takt time before capital expenditure. Training operators and maintenance staff on new equipment reduces downtime and unsafe workarounds after installation.',
    ],
    [
      q(
        'What device often coordinates conveyors and robots with deterministic scan cycles?',
        ['Programmable logic controller (PLC)', 'Consumer graphics tablet only', 'Plain spreadsheet without I/O', 'Passive mechanical pulley'],
        0,
        'PLCs synchronize line equipment including robots via I/O and industrial fieldbuses.',
      ),
      q(
        'Why are interlocked safety doors and light curtains used in robot cells?',
        ['Stop or inhibit robot motion when humans enter hazardous space', 'Increase cycle time arbitrarily', 'Improve Wi-Fi coverage only', 'Replace all operator training'],
        0,
        'Safety devices prevent exposure to hazardous motion during cell access.',
      ),
      q(
        'What does takt time represent in production?',
        ['Available production time divided by customer demand rate', 'Motor winding temperature', 'Battery charge cycles only', 'Camera frame exposure'],
        0,
        'Takt time sets the pace each unit must be completed to meet demand.',
      ),
      q(
        'Why is consistent part presentation important to robot cells?',
        ['Reduces mis-picks and crashes from unexpected part pose variation', 'Eliminates need for any fixtures', 'Removes all vision systems always', 'Guarantees infinite payload'],
        0,
        'Repeatable part location simplifies grasp planning and improves reliability.',
      ),
      q(
        'What is machine tending in industrial robotics?',
        ['Loading and unloading parts from CNC or other machines', 'Painting office walls only', 'Delivering mail internally', 'Monitoring social media feeds'],
        0,
        'Tending robots supply and remove workpieces from automated machine tools.',
      ),
      q(
        'What purpose does MES integration serve alongside robots?',
        ['Production tracking, traceability, and analytics on the shop floor', 'Personal email hosting', 'Game streaming', 'Home lighting control'],
        0,
        'MES systems collect operational data including robot cycle and quality events.',
      ),
      q(
        'What is lockout/tagout (LOTO) used for during maintenance?',
        ['Isolate energy sources so equipment cannot start unexpectedly', 'Speed up all cycles during service', 'Bypass safety interlocks permanently', 'Calibrate cameras automatically'],
        0,
        'LOTO protects workers by controlling hazardous energy during servicing.',
      ),
      q(
        'Why simulate throughput before purchasing a robot cell?',
        ['Verify reach, cycle time, and bottlenecks meet production targets', 'Eliminate all risk assessments', 'Remove need for PLCs', 'Disable operator training'],
        0,
        'Simulation validates that proposed automation achieves required takt and layout fit.',
      ),
      q(
        'What does a vision inspection system do in automated lines?',
        ['Detect defects or verify assembly and record results per unit', 'Replace all mechanical tooling', 'Supply hydraulic fluid', 'Control building HVAC only'],
        0,
        'Vision checks quality and can trigger reject routing without manual inspection.',
      ),
      q(
        'Which standard family addresses industrial robot safety requirements?',
        ['ISO 10218 and related guidance such as ISO/TS 15066 for collaboration', 'HTML5 specification only', 'JPEG compression standard', 'Unicode character set'],
        0,
        'ISO 10218 defines safety requirements for industrial robot systems and integration.',
      ),
    ],
  ),
  lesson(
    'Collaborative Robots',
    [
      'Collaborative robots (cobots) are designed to work near humans without traditional hard guarding in suitable applications. They incorporate force and torque sensing, power-limited motion, and rounded geometries to reduce injury risk on contact. Cobots trade some speed and payload compared to larger industrial arms for flexibility and easier redeployment.',
      'Safety standards ISO/TS 15066 define collaborative operation modes: safety-rated monitored stop, hand guiding, speed and separation monitoring, and power and force limiting. Risk assessment determines which mode is appropriate for each task, considering tooling, workpiece hazards, and operator positions. Not every task is suitable for uncaged collaboration.',
      'Programming cobots often uses teach pendants with hand guiding: an operator physically moves the arm through waypoints that the system records. Graphical interfaces and lightweight scripting lower the barrier for small and medium enterprises without dedicated robotics engineers. Quick setup supports high-mix, low-volume production scenarios.',
      'Force-limited control detects unexpected contacts and stops or retreats rather than pushing through. Payload and speed must stay within certified limits for the chosen collaborative mode. Sharp tools, high inertia workpieces, or processes involving heat and chemicals may still require guarding despite the cobot label.',
      'Cobots excel at repetitive assist tasks: machine tending, screw driving, packaging, and quality checks beside operators. Human-robot teams leverage human flexibility for variation while the robot handles ergonomic strain and consistency. Workflow design must avoid placing humans in pinch points even with collaborative features enabled.',
      'Integration with vision, conveyor tracking, and mobile platforms expands cobot use cases. Fleet software monitors cycles and diagnostics across multiple lightweight arms on a shop floor. Training emphasizes safe approach distances, proper mode selection, and understanding that collaboration is application-dependent, not automatic for all installations.',
    ],
    [
      q(
        'What primary design goal distinguishes cobots from traditional industrial arms?',
        ['Safe operation near humans in defined collaborative modes', 'Maximum speed regardless of contact', 'No sensing of any kind', 'Exclusive underwater operation'],
        0,
        'Cobots emphasize human-proximate operation with force/speed limiting and safety modes.',
      ),
      q(
        'Which ISO document defines collaborative robot operation modes and force limits?',
        ['ISO/TS 15066', 'ISO 9001 recipe book', 'JPEG 2000', 'RFC 791 only'],
        0,
        'ISO/TS 15066 specifies collaborative modes and biomechanical limit guidance.',
      ),
      q(
        'What is hand guiding as a collaborative mode?',
        ['Operator manually moves the robot while it records waypoints or assists with reduced force', 'Remote control from another country only', 'Autonomous racing mode', 'Permanent full-speed operation'],
        0,
        'Hand guiding lets users teach paths by physically guiding the arm under controlled conditions.',
      ),
      q(
        'Why might sharp tooling still require guarding on a cobot cell?',
        ['Workpiece and tool hazards remain even if the arm is force-limited', 'Cobots eliminate all cutting risks automatically', 'Guards are never used with cobots', 'Sharp tools improve force sensing'],
        0,
        'Collaborative arm features do not remove hazards from sharp or hot process tooling.',
      ),
      q(
        'What trade-off do cobots often accept versus larger industrial robots?',
        ['Lower speed and payload for easier deployment and human proximity', 'Higher payload than any industrial arm', 'No programming interface', 'Removal of all safety standards'],
        0,
        'Cobots prioritize safe interaction and flexibility over maximum performance specs.',
      ),
      q(
        'What should a risk assessment determine for cobot applications?',
        ['Appropriate collaborative mode and required safeguards for the specific task', 'Only marketing slogans', 'Office paint colors', 'Employee lunch menus'],
        0,
        'Each application needs analysis of hazards, tooling, and human positions per standards.',
      ),
      q(
        'How does force-limited control typically respond to unexpected contact?',
        ['Stop or retreat rather than continue pushing through the obstacle', 'Increase torque to break through', 'Disable all brakes permanently', 'Ignore sensor readings'],
        0,
        'Contact detection triggers stops or compliant retreat to limit injury risk.',
      ),
      q(
        'In which production scenario do cobots especially shine?',
        ['High-mix, low-volume tasks needing quick redeployment beside operators', 'Only continuous mining at maximum payload', 'Underwater oil drilling exclusively', 'Tasks requiring no human involvement ever'],
        0,
        'Flexible setup suits varied small-batch work alongside human coworkers.',
      ),
      q(
        'Why avoid placing humans in pinch points even with cobot safety features?',
        ['Crush and pinch hazards may remain from fixtures and workpieces', 'Pinch points are always safe with cobots', 'Cobots eliminate all fixture geometry', 'Standards prohibit any fixtures near cobots'],
        0,
        'Collaborative arm limits do not remove mechanical pinch hazards from cell layout.',
      ),
      q(
        'What does speed and separation monitoring require?',
        ['Maintain protective separation or reduce speed when humans approach', 'Run at maximum speed always', 'Disable all sensors', 'Remove emergency stops'],
        0,
        'This mode adjusts motion based on measured distance to personnel in the workspace.',
      ),
    ],
  ),
  lesson(
    'Robot Safety',
    [
      'Robot safety protects operators, maintenance staff, and bystanders from hazardous energy and unexpected motion. Risk assessment identifies hazards, estimates severity and probability, and selects mitigation: guarding, interlocks, reduced speed modes, training, and administrative controls. Safety is designed into the cell from layout through commissioning, not added as an afterthought.',
      'Emergency stop devices must be reachable, clearly marked, and wired to remove drive power or trigger safe stopping according to category standards. Reset after e-stop requires deliberate action and verification that the hazard is cleared. Frequent nuisance trips erode compliance if operators bypass interlocks—design should balance sensitivity with operational practicality.',
      'Functional safety standards such as ISO 13849 and IEC 62061 classify safety-related control systems by performance level or safety integrity level. Dual-channel monitoring, tested relays, and safe torque off (STO) drives implement fail-safe behavior when components fault. Software alone without rated hardware cannot claim safety-critical compliance.',
      'Collaborative applications add biomechanical limits on contact forces but do not eliminate all risks from tooling, projectiles, or trapped limbs. Lockout/tagout isolates pneumatic, hydraulic, electrical, and gravitational energy during maintenance. Teach mode and manual jog require reduced speed and explicit enable controls to prevent surprises.',
      'Cybersecurity intersects with safety as networked robots become remote-service enabled. Unauthorized access could alter speeds, disable interlocks, or exfiltrate production data. Network segmentation, authenticated updates, and monitoring for anomalous commands reduce attack surfaces on connected automation.',
      'Training and procedures complete the safety system: operators learn authorized entry, reset sequences, and reporting of near misses. Regular drills and audits verify interlocks, light curtain alignment, and e-stop function. Documentation of changes after retrofit ensures safety circuits still match the risk assessment for the current configuration.',
    ],
    [
      q(
        'What is the first step in designing a safe robot installation?',
        ['Risk assessment identifying hazards and mitigation strategies', 'Maximum speed tuning only', 'Removing all guards for convenience', 'Skipping operator training'],
        0,
        'Structured risk assessment drives guarding, controls, and procedures matched to hazards.',
      ),
      q(
        'What must emergency stop circuits typically cause?',
        ['Safe removal or inhibition of hazardous motion and drive energy', 'Automatic restart without checks', 'Increased speed to clear the area', 'Permanent deletion of all programs'],
        0,
        'E-stops initiate a safe state; reset requires deliberate verification afterward.',
      ),
      q(
        'What does safe torque off (STO) on a drive accomplish?',
        ['Prevents torque-producing energy to the motor for safe conditions', 'Increases maximum acceleration always', 'Calibrates lidar automatically', 'Opens safety gates'],
        0,
        'STO removes motive power so the motor cannot actively drive motion.',
      ),
      q(
        'Why can software-only interlocks fail functional safety requirements?',
        ['Rated safety requires certified hardware paths independent of general software', 'Software never fails', 'All PLCs are non-deterministic always', 'Guards replace all electrical design'],
        0,
        'Standards mandate validated hardware channels for safety-critical stop functions.',
      ),
      q(
        'What is lockout/tagout intended to prevent during maintenance?',
        ['Unexpected energization or startup while workers service equipment', 'Routine production cycles', 'Quality inspections during run', 'Normal operator resets'],
        0,
        'LOTO controls hazardous energy so machines stay safe during service work.',
      ),
      q(
        'Why is bypassing light curtains a serious safety violation?',
        ['It removes protection against motion while humans are in the hazard zone', 'It improves cycle time safely always', 'Light curtains are decorative only', 'Standards require bypassing during normal run'],
        0,
        'Defeating interlocks exposes people to robot motion without intended safeguards.',
      ),
      q(
        'How does cybersecurity relate to robot safety?',
        ['Unauthorized control could alter motion or disable safeguards on networked robots', 'Cybersecurity applies only to websites', 'Robots cannot be networked', 'Encryption removes need for physical guards'],
        0,
        'Connected robots need protection against commands that could create hazardous states.',
      ),
      q(
        'What should manual teach or jog modes enforce?',
        ['Reduced speed and explicit enabling so motion is predictable', 'Full industrial speed always', 'No operator presence allowed ever', 'Automatic welding without shields'],
        0,
        'Teaching modes limit hazard energy while operators work near the arm.',
      ),
      q(
        'Which standard family addresses safety-related parts of control systems?',
        ['ISO 13849 and IEC 62061', 'HTML living standard only', 'MPEG-4 video codec', 'Unicode emoji list'],
        0,
        'These standards define performance levels for safety control architectures.',
      ),
      q(
        'Why document configuration changes after robot cell retrofits?',
        ['Safety circuits and risk assessments must match the current installed state', 'Documentation slows robots down mechanically', 'Audits are optional always', 'Changes never affect safety devices'],
        0,
        'Updated records ensure guards, interlocks, and assessments reflect actual equipment.',
      ),
    ],
  ),
  lesson(
    'Simulation and Testing',
    [
      'Simulation accelerates robot development by validating mechanics, control, and autonomy before expensive hardware commits. Physics engines model contacts, friction, and actuator limits; sensor simulators generate synthetic lidar, cameras, and IMU data from virtual environments. Gazebo, Isaac Sim, Webots, and vendor-specific tools integrate with ROS and commercial offline programming packages.',
      'Digital twins mirror live assets with updated parameters from field data, supporting predictive maintenance and what-if scenario analysis. When twin models track real wear and calibration drift, simulated tests better predict on-floor behavior. Twins also train operators and debug fault scenarios without stopping production.',
      'Unit tests verify isolated components: kinematics libraries, planners, inverse Jacobian implementations, and message parsers. Property-based tests explore edge cases in joint limits and singularities. Continuous integration runs these tests on every code change to catch regressions early.',
      'Integration and hardware-in-the-loop tests connect controllers to simulated plants or partial real subsystems. Motor drivers on a bench rig spin loads while safety systems remain de-energized for initial tuning. Graduated bring-up moves from single-axis jog to full-speed production sequences under supervision.',
      'Scenario-based validation enumerates operational cases: empty vs full payload, slippery floors, sensor dropout, and emergency stop during motion. Monte Carlo variation in simulation estimates success probabilities under parameter uncertainty. Field pilots on limited routes gather metrics before granting broader autonomy permissions.',
      'Recording and playback of rosbags or vendor logs reproduce failures for offline debugging. Repeatable test datasets benchmark perception algorithms across software versions. Clear pass/fail criteria—tracking error bounds, collision counts, cycle time variance—objectively gate releases from staging to production deployment.',
    ],
    [
      q(
        'What primary benefit does simulation offer early in robot development?',
        ['Validate design and software with lower cost and risk before full hardware build', 'Eliminate all real-world testing forever', 'Replace all safety standards', 'Guarantee perfect models without calibration'],
        0,
        'Simulation catches design and control issues virtually, saving time and hardware risk.',
      ),
      q(
        'What is a digital twin in robotics context?',
        ['Virtual model synchronized with a live robot for analysis and prediction', 'A duplicate physical robot always', 'Only a PDF manual', 'A non-interactive screenshot'],
        0,
        'Twins mirror real assets with data feedback for maintenance and scenario testing.',
      ),
      q(
        'What should unit tests on kinematics libraries verify?',
        ['Correct forward/inverse results and behavior at joint limits', 'Office Wi-Fi password strength', 'Employee badge colors', 'Building HVAC schedules'],
        0,
        'Kinematics tests ensure pose calculations remain accurate across valid configurations.',
      ),
      q(
        'What is hardware-in-the-loop (HIL) testing?',
        ['Running control code against simulated or partial real hardware subsystems', 'Testing only marketing brochures', 'Operating robots without e-stops', 'Skipping integration entirely'],
        0,
        'HIL connects controllers to plant models or bench rigs for realistic validation.',
      ),
      q(
        'Why run scenario tests with sensor dropout simulated?',
        ['Verify graceful degradation and safe stops when data is unreliable', 'Prove sensors never fail in reality', 'Increase speed during faults', 'Disable all logging'],
        0,
        'Robust systems must handle missing or bad sensor data without unsafe motion.',
      ),
      q(
        'What do physics engines in robot simulators model?',
        ['Contacts, friction, masses, and actuator constraints affecting motion', 'Only text fonts on UI', 'Corporate email routing', 'Static billboard images without dynamics'],
        0,
        'Physics simulation approximates forces and interactions robots experience physically.',
      ),
      q(
        'What is the purpose of recording rosbags or vendor logs during field tests?',
        ['Replay sensor and command data offline to reproduce and debug failures', 'Delete all historical data', 'Increase motor voltage automatically', 'Replace risk assessments'],
        0,
        'Recorded data enables repeatable offline analysis of incidents seen on the robot.',
      ),
      q(
        'What should gate a software release from staging to production deployment?',
        ['Defined pass/fail metrics such as tracking error, collisions, and cycle variance', 'Random operator preference only', 'Logo color changes', 'Number of meeting minutes'],
        0,
        'Objective criteria ensure releases meet safety and performance thresholds.',
      ),
      q(
        'Why use Monte Carlo variation in simulation tests?',
        ['Estimate performance distributions under uncertain parameters', 'Eliminate all uncertainty in real robots', 'Avoid testing edge cases', 'Guarantee identical runs every time'],
        0,
        'Randomized parameters reveal sensitivity and probability of failure modes.',
      ),
      q(
        'What graduated bring-up practice reduces commissioning risk?',
        ['Progress from single-axis jog to supervised full-speed sequences', 'Immediate full-speed production on day one', 'Skip all bench testing', 'Disable interlocks for faster tuning'],
        0,
        'Stepwise commissioning isolates faults before full operational speeds and loads.',
      ),
    ],
  ),
  lesson(
    'Maintenance',
    [
      'Preventive maintenance schedules keep robots reliable and reduce unplanned downtime in production. Manufacturers specify intervals for lubricating joints, inspecting belts and cables, replacing filters, and checking battery health on mobile platforms. Condition monitoring tracks vibration, motor current signatures, and temperature trends to predict failures before catastrophic stops.',
      'Calibration drift affects encoders, vision systems, and force-torque sensors used for precision tasks. Regular calibration against known references restores accuracy for grasping, welding, and inspection. After mechanical repairs—gearbox replacement, belt tension adjustment—kinematic and tool-center-point calibration must be repeated and documented.',
      'Spare parts strategy balances inventory cost against mean time to repair. Critical items include drive modules, encoders, batteries, and proprietary controller components with long lead times. Standardizing on robot models across a site simplifies spare pooling and technician training.',
      'Software updates patch security vulnerabilities and improve algorithms but require validation on staging hardware before production rollout. Rollback plans and version pinning prevent a bad update from halting an entire line. Configuration backups preserve tuned parameters, maps, and taught paths.',
      'Cleaning removes debris that abrades seals, clogs cooling fans, and contaminates optical sensors. In food, pharma, and cleanroom environments, washdown-rated designs and approved lubricants meet regulatory hygiene requirements. Cable dress and strain relief inspection prevents intermittent faults from repeated flexing.',
      'Maintenance logs tie work orders to fault codes, parts consumed, and downtime duration. Analytics on recurring failures inform design improvements and operator training gaps. Safe maintenance always follows lockout/tagout and vendor procedures; rushing service without isolating energy causes serious injury incidents.',
    ],
    [
      q(
        'What is the goal of preventive maintenance on robots?',
        ['Reduce unplanned downtime by servicing components on scheduled intervals', 'Eliminate all calibration forever', 'Maximize unplanned stops', 'Remove all spare parts inventory'],
        0,
        'Scheduled care catches wear before it causes unexpected production halts.',
      ),
      q(
        'Why recalibrate tool center point after mechanical repairs?',
        ['Repairs change kinematics or tooling geometry affecting accuracy', 'Calibration never changes after shipping', 'Repairs only affect paint color', 'TCP is unrelated to grasping'],
        0,
        'Mechanical changes alter where the tool frame sits relative to programmed paths.',
      ),
      q(
        'What does condition monitoring analyze to predict failures?',
        ['Trends in vibration, current, temperature, and similar health indicators', 'Only employee vacation schedules', 'Website traffic spikes', 'Office supply orders'],
        0,
        'Abnormal trends in operational signals often precede component failure.',
      ),
      q(
        'Why validate software updates on staging hardware first?',
        ['Catch regressions before disrupting production lines', 'Updates never affect robot behavior', 'Production is the only test environment needed', 'Rollback is impossible always'],
        0,
        'Staging tests reduce risk of a bad release stopping live operations.',
      ),
      q(
        'What maintenance task helps prevent intermittent sensor faults on mobile robots?',
        ['Inspecting cable dress and strain relief for wear or pinch damage', 'Ignoring all connectors', 'Maximizing cable tension always', 'Removing all shielding'],
        0,
        'Flex fatigue and poor routing cause difficult intermittent electrical faults.',
      ),
      q(
        'Why maintain spare inventory for long-lead proprietary components?',
        ['Reduce mean time to repair when critical parts fail', 'Increase downtime deliberately', 'Eliminate all documentation', 'Avoid training technicians'],
        0,
        'On-hand spares shorten repairs when specialized parts cannot be sourced instantly.',
      ),
      q(
        'What should maintenance logs record for continuous improvement?',
        ['Fault codes, parts used, downtime, and actions taken', 'Only cafeteria menus', 'Random personal notes without structure', 'Unrelated IT ticket numbers only'],
        0,
        'Structured logs reveal patterns guiding design fixes and training needs.',
      ),
      q(
        'Why use washdown-rated designs in food or pharma robot cells?',
        ['Meet hygiene regulations and resist cleaning chemicals and moisture', 'Increase electrical hazard intentionally', 'Eliminate all seals', 'Remove need for any maintenance'],
        0,
        'Regulated environments require equipment that survives sanitary cleaning procedures.',
      ),
      q(
        'When should battery health checks be emphasized on mobile robots?',
        ['During scheduled service to avoid unexpected runtime loss in operation', 'Never—batteries do not degrade', 'Only after complete fleet replacement', 'Only during software compiles'],
        0,
        'Aging packs lose capacity; monitoring prevents missions failing mid-route.',
      ),
      q(
        'What safety practice is mandatory before hands-on robot maintenance?',
        ['Lockout/tagout and vendor isolation procedures for hazardous energy', 'Jogging at full speed to test reflexes', 'Bypassing interlocks for access', 'Live troubleshooting on energized pinch points'],
        0,
        'LOTO and proper procedures protect technicians from unexpected energization.',
      ),
    ],
  ),
  lesson(
    'Future of Robotics',
    [
      'Advances in machine learning enable robots to perceive unstructured environments and generalize across objects and layouts better than hand-tuned pipelines alone. Deep learning improves vision-based picking, semantic mapping, and speech interfaces for human-robot interaction. Sim-to-real transfer techniques train policies in simulation and adapt them to physical hardware with reduced manual tuning.',
      'Edge AI hardware brings inference closer to sensors, lowering latency for grasp detection and obstacle avoidance on battery-powered platforms. Neuromorphic and specialized accelerators may further improve energy efficiency for always-on perception. Cloud connectivity still supports fleet analytics, over-the-air updates, and heavy model training while critical safety loops remain local.',
      'Humanoid and general-purpose robot platforms attract investment for logistics, home assistance, and flexible manufacturing. Bipedal locomotion and dexterous hands remain hard problems combining mechanics, control, and rich sensing. Economic viability depends on reliability, cost, and clear tasks where general morphology beats specialized designs.',
      'Soft robotics uses compliant materials and fluidic actuators for safe interaction and adaptive grasping of delicate objects. Miniature medical robots and continuum manipulators navigate confined anatomical spaces. Bio-inspired designs study locomotion and sensing strategies from animals to improve agility on sand, rubble, or wet surfaces.',
      'Regulation and ethics evolve with autonomous systems in public spaces: liability for accidents, data privacy from cameras, and workforce displacement concerns shape adoption. Standards bodies work on certification frameworks for autonomous mobile robots and AI-enabled industrial equipment. Transparent logging and human oversight remain central to trustworthy deployment.',
      'Sustainability influences future designs: energy-efficient drives, recyclable materials, longer service life, and remanufacturing of modules reduce environmental impact. Human-robot collaboration is expected to expand as sensing and safety technology improve, augmenting workers rather than replacing entire job categories uniformly. Continuous learning across careers in robotics will blend classical engineering with data-driven methods.',
    ],
    [
      q(
        'How is machine learning changing robotic perception?',
        ['It improves generalization in vision, mapping, and interaction beyond hand-tuned rules alone', 'It removes all need for sensors', 'It eliminates safety requirements', 'It prevents simulation use'],
        0,
        'Learning-based methods handle variability in objects and scenes more flexibly than fixed pipelines.',
      ),
      q(
        'What is sim-to-real transfer aimed at?',
        ['Training policies in simulation and adapting them to work on physical robots', 'Moving robots only in virtual worlds forever', 'Eliminating all real hardware', 'Replacing calibration permanently'],
        0,
        'Sim-to-real reduces manual tuning by bridging simulated training and physical deployment.',
      ),
      q(
        'Why deploy edge AI hardware on mobile robots?',
        ['Lower inference latency and reduce dependence on cloud for time-critical perception', 'Increase battery drain always with no benefit', 'Disable all local processing', 'Remove cameras entirely'],
        0,
        'On-board inference reacts faster and works when network links are poor or absent.',
      ),
      q(
        'What challenge limits immediate widespread use of general-purpose humanoid robots?',
        ['Reliability, cost, and difficulty of locomotion/manipulation in unstructured settings', 'Lack of any commercial interest', 'Absence of compute hardware', 'Prohibition on all research'],
        0,
        'Humanoids face tough mechanical and control problems before economical daily deployment.',
      ),
      q(
        'What advantage do soft robotic actuators offer?',
        ['Compliance enables safer contact and adaptive grasping of delicate items', 'They are always rigid and high-force only', 'They cannot be controlled programmatically', 'They replace all vision systems'],
        0,
        'Soft structures deform safely and conform to varied object shapes during grasp.',
      ),
      q(
        'Which societal concern accompanies autonomous robots in public spaces?',
        ['Liability, privacy, and workforce impact require policy and design attention', 'No concerns once robots are autonomous', 'Only aesthetic branding issues', 'Elimination of all standards bodies'],
        0,
        'Deployment raises legal, ethical, and economic questions beyond technical performance.',
      ),
      q(
        'Why keep critical safety control loops local rather than only in the cloud?',
        ['Network latency and outages must not delay emergency stopping or stabilization', 'Cloud is always faster than local compute', 'Safety loops cannot run on embedded hardware', 'Local control is banned by standards'],
        0,
        'Safety-critical functions need deterministic local response independent of connectivity.',
      ),
      q(
        'How might sustainability influence future robot design?',
        ['Efficient drives, durable modules, and recyclable materials reduce lifecycle impact', 'Shorter life and more waste are goals', 'Energy use is irrelevant to robotics', 'Maintenance should be impossible'],
        0,
        'Environmental goals push efficiency, longevity, and responsible materials choices.',
      ),
      q(
        'What role is cloud connectivity still expected to play in future fleets?',
        ['Analytics, training heavy models, and over-the-air updates across deployed robots', 'Exclusive real-time motor control every cycle', 'Replacement of all edge compute', 'Elimination of data logging'],
        0,
        'Cloud supports fleet intelligence while time-critical control stays on the robot.',
      ),
      q(
        'What skill blend will robotics careers increasingly require?',
        ['Classical mechanics/control plus data-driven AI and software engineering', 'Only manual welding with no software', 'Only graphic design skills', 'No need for safety or ethics awareness'],
        0,
        'Future robotics integrates traditional engineering with ML, software, and responsible deployment.',
      ),
    ],
  ),
]
