import { webDevelopmentSections } from './learn/web-development.mjs'
import { roboticsSections } from './learn/robotics.mjs'
import { aiBusinessSections } from './learn/ai-business.mjs'
import { programmingSections } from './learn/programming-patterns.mjs'

const courses = [
  {
    slug: 'web-development-fundamentals',
    title: 'Web Development Fundamentals',
    level: 'Beginner',
    duration: '6 weeks',
    description:
      'Learn HTML, CSS, JavaScript, and modern web practices to build professional websites from scratch.',
    studySections: webDevelopmentSections,
  },
  {
    slug: 'introduction-to-robotics',
    title: 'Introduction to Robotics',
    level: 'Intermediate',
    duration: '8 weeks',
    description:
      'Explore robotics concepts, automation basics, and hands-on projects for real-world applications.',
    studySections: roboticsSections,
  },
  {
    slug: 'ai-for-business',
    title: 'AI for Business',
    level: 'Beginner',
    duration: '4 weeks',
    description:
      'Understand how AI tools can improve workflows, decision-making, and business efficiency.',
    studySections: aiBusinessSections,
  },
  {
    slug: 'advanced-programming-patterns',
    title: 'Advanced Programming Patterns',
    level: 'Advanced',
    duration: '10 weeks',
    description:
      'Master scalable code architecture, best practices, and advanced programming techniques.',
    studySections: programmingSections,
  },
]

const output = `// Auto-generated by scripts/generateLearnContent.mjs
export type QuizQuestion = {
  question: string
  options: readonly string[]
  correctIndex: number
  explanation: string
}

export type StudySection = {
  title: string
  explanation: readonly string[]
  quiz: readonly QuizQuestion[]
}

export type LearnCourseContent = {
  slug: string
  title: string
  level: string
  duration: string
  description: string
  studySections: readonly StudySection[]
}

export const learnCourseContent = ${JSON.stringify(courses, null, 2)} as const

export const getLearnCourse = (slug: string) =>
  learnCourseContent.find((course) => course.slug === slug)

export const getCourseQuestionCount = (course: LearnCourseContent) =>
  course.studySections.reduce((total, section) => total + section.quiz.length, 0)

export const getCourseLessonCount = (course: LearnCourseContent) =>
  course.studySections.length
`

import { writeFileSync } from 'fs'
import { fileURLToPath } from 'url'
import { dirname, join } from 'path'

const __dirname = dirname(fileURLToPath(import.meta.url))
writeFileSync(join(__dirname, '../src/data/learnContent.ts'), output, 'utf8')

for (const course of courses) {
  const q = course.studySections.reduce((t, s) => t + s.quiz.length, 0)
  console.log(`${course.title}: ${course.studySections.length} lessons, ${q} questions`)
}

console.log('Generated src/data/learnContent.ts')
